
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-23T17:41:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "10d69695b94700251072d3304afd64c0dc9d791b",
 "version": "2.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
